# Generated by Django 4.0.6 on 2023-04-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role_delete_event_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Viewer'), ('2', 'Admin'), ('3', 'Performer'), ('4', 'Modrator')], default='1', max_length=20),
        ),
        migrations.DeleteModel(
            name='role',
        ),
    ]
